title: Shrawan Matrubai
logo: /assets/New Project.png 
description: My portfolio highlights my expertise in C++, DSA, and full-stack development, with projects like a fitness tracker app using React & MongoDB. I have a strong foundation in AI & ML, backed by a BE in AIML from BMSCE. I’m joining Iron Mountain as an Associate Software Engineer intern (April 2025)
show_downloads: true
theme: jekyll-theme-minimal
